baseURL: ""
languageCode: "ja-JP"
title: "CloudNative Days Tokyo 2020"
theme: "hugo-conference"

publishDir: "docs"

params:
  Name: "CloudNative Days Tokyo 2020"
  Description: "Conference description"
  Date: "SEPT 8-9, 2020"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: " Online"
  Address: "TBD"
  City:  ""
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"
  Sections:
    - about
    - contact
  Titles:
    about: "About"
    contact: "Contact"
  customCSS: ["css/custom.css"]
  CallToAction:
    text: "Call for Proposals"
    link: "https://docs.google.com/forms/d/e/1FAIpQLSd_n9AbGr3wTLNN-M8C_YmMpfK8xCON8baq4_FVI7ysciLlnA/viewform"
