name: pull request

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.0'

      - name: Build
        run: hugo

      - name: Comment succeeded
        uses: mshick/add-pr-comment@v1
        if: success()
        with:
          message: |
            Build succeeded!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment failed
        uses: mshick/add-pr-comment@v1
        if: failure()
        with:
          message: "Build failed😗"
          repo-token: ${{ secrets.GITHUB_TOKEN }}